In [1]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [11]:
K = np.array(range(0,10))

In [12]:
K

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.median(K) #中位數

4.5

In [14]:
K.cumsum() #連加

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [17]:
K.prod() #全部乘起來

0

In [18]:
K.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [19]:
L=np.arange(1,10)

In [20]:
L

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
L.cumprod()

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [22]:
N = L.reshape(3,3)

In [23]:
N

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
N.mean()

5.0

In [26]:
N.mean(axis=0) #行的平均值

array([4., 5., 6.])

In [27]:
N.mean(axis=1) #列的

array([2., 5., 8.])

In [54]:
np.random.seed(1) #亂數產生器設定seed為1 #只能維持一次的效果 #但後面的也會受影響會照順序

In [53]:
np.random.randint(10)

5

In [63]:
num=0
np.random.seed(1)
while(num<5):
    print(np.random.randint(10))
    num+=1

5
8
9
5
0


In [65]:
np.random.randn() #這個也會受到seed影響

-1.6545154524065693

In [71]:
np.mean(np.random.randn(100,100))

0.009769148030462489

In [80]:
S=np.array(range(1,10))
print(S)
np.random.choice(S,5,replace = False) #隨機從S中選出5個 #replace就是能否重複選取

[1 2 3 4 5 6 7 8 9]


array([8, 5, 3, 9, 4])

In [86]:
P=[0,0,0,0.1,0.5,0.2,0.1,0,0.1]

In [87]:
np.random.choice(S,5,p=P,replace=False) #P是機率

array([5, 6, 9, 7, 4])